# Generated by Django 5.2 on 2025-06-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currence_vacancy', to='dictionary.currency'),
        ),
        migrations.AddField(
            model_name='resume',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.region'),
        ),
        migrations.AddField(
            model_name='resumecontact',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeeducation',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeemploymenttype',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.employmenttype'),
        ),
        migrations.AddField(
            model_name='resumeemploymenttype',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_types', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.language'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.languagelevel'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumescheduletype',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.scheduletype'),
        ),
        migrations.AddField(
            model_name='resumescheduletype',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_types', to='resumes.resume'),
        ),
    ]
