# Generated by Django 5.2 on 2025-05-18 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.currency'),
        ),
        migrations.AddField(
            model_name='resumecontact',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeeducation',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeemploymenttype',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.employmenttype'),
        ),
        migrations.AddField(
            model_name='resumeemploymenttype',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_types', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.language'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.languagelevel'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumepassport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.city'),
        ),
        migrations.AddField(
            model_name='resumepassport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.country'),
        ),
        migrations.AddField(
            model_name='resumepassport',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.region'),
        ),
        migrations.AddField(
            model_name='resumepassport',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumescheduletype',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_types', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumescheduletype',
            name='schedule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.scheduletype'),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dictionary.skill'),
        ),
    ]
