# Generated by Django 5.2 on 2025-05-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_branch'),
        ('resumes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currence_vacancy', to='dictionary.currency'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='version',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='resumepassport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.city'),
        ),
        migrations.AlterField(
            model_name='resumepassport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.country'),
        ),
        migrations.AlterField(
            model_name='resumepassport',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resumepassport',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.region'),
        ),
    ]
