# Generated by Django 5.2 on 2025-06-02 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_resumestatus'),
        ('resumes', '0003_alter_resume_created_by_alter_resume_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeemploymenttype',
            old_name='employment_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resumeexperience',
            old_name='job_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='resumescheduletype',
            old_name='schedule_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='resumeeducation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resumeeducation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], default='М', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(default='Иванов', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='dictionary.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeeducation',
            name='end_year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeeducation',
            name='start_year',
            field=models.IntegerField(default=2015),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResumePassport',
        ),
    ]
