# Generated by Django 5.2 on 2025-05-29 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0003_resumestatus'),
        ('resumes', '0003_alter_resume_created_by_alter_resume_currency_and_more'),
        ('vacancies', '0003_alter_vacancy_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recrutiers', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recrutiers', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='resumes.resume')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumevacancies', to='dictionary.resumestatus')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancies.vacancy')),
            ],
        ),
    ]
