# Generated by Django 5.2 on 2025-06-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        ('relations', '0001_initial'),
        ('resumes', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteresume',
            name='recruiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteresume',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recrutiers', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='favoritevacancy',
            name='recruiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritevacancy',
            name='vacancy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recrutiers', to='vacancies.vacancy'),
        ),
        migrations.AddField(
            model_name='resumevacancy',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumevacancy',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumevacancies', to='dictionary.resumestatus'),
        ),
        migrations.AddField(
            model_name='resumevacancy',
            name='vacancy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancies.vacancy'),
        ),
    ]
