# Generated by Django 5.2 on 2025-05-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_need_higher_education', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='dictionary.currency')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='dictionary.employmenttype')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='dictionary.experience')),
                ('format_of_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='dictionary.formatofwork')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='dictionary.jobtitle')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='dictionary.scheduletype')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancy_branches', to='dictionary.branch')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grades_vacancy', to='dictionary.grade')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancy_skills', to='dictionary.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='vacancies.vacancy')),
            ],
        ),
    ]
