# Generated by Django 5.2 on 2025-05-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='is_active',
            new_name='is_open',
        ),
    ]
